"""empty message

Revision ID: 77da9c77fcb2
Revises: bdc00c35e70e
Create Date: 2021-08-27 07:29:36.710034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77da9c77fcb2'
down_revision = 'bdc00c35e70e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('father_id', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('mother_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person', 'person', ['mother_id'], ['id'])
    op.create_foreign_key(None, 'person', 'person', ['father_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'mother_id')
    op.drop_column('person', 'father_id')
    # ### end Alembic commands ###
